=encoding utf8

=head1 Buffy - a Few Good Slayers

=head2 About

I<Buffy: a Few Good Slayers> is a new piece of Buffy fanfiction set in a forked
version of the Buffy universe, starting from the end of the third season of
Buffy, while taking place many years later in 2014/2015 Sunnydale. The idea and
concept were created by L<Shlomi Fish|http://www.shlomifish.org/>.

=head2 What happened from 2000/2001

Faith turned out to have been a good slayer after all, and prevented the mayor
from ascending properly in the last minute. She joins forces with Buffy and the
Scooby gang, as an equal co-slayer.

Faith starts dating Xander, and they end up falling in love. Xander grows more
confident, and after training and encouragement from Buffy and Faith becomes
the world's first qualified '''male''' slayer, paving the road for other male
slayers.

Faith and Xander marry after college, and have children. Buffy is able to cure
Angel out of his vampiredom, and he becomes a slayer, marries Buffy and they
have children.

Willow cures Oz out of his werewolfness, becomes Dr. Willow Rosenberg and one
of the most powerful witches (or wizards) known on Earth. Oz becomes a wizard
too - he and Willow marry and have some children.

Giles becomes the principal of Sunnydale high school where the whole gang
is working as teachers, teaching next generations of budding slayers,
witches/wizards, and watchers, making Sunnydale the Mecca of the slaying
world.

L<https://en.wikipedia.org/wiki/Cordelia_Chase> moves out of Sunnydale, becomes
a scholar (Ph.D. + Professor), marries, has children, and mostly stays out of
the way of slaying. She remains friends with the gang and comes to visit
sometimes.

=head2 Theme

=cut
